# ipsec.conf - strongSwan IPsec configuration file

# basic configuration

config setup
	# strictcrlpolicy=yes
	# uniqueids = no

# Add connections here.
conn %default
	ikelifetime=60m
	keylife=20m
	rekeymargin=3m
	keyingtries=1
	mobike=no
	keyexchange=ikev2
	authby=pubkey

conn host-host
	left=192.168.56.102
	leftcert=/etc/ipsec.d/certs/servercert.pem
	leftid="C=ES, ST=Murcia, O=UMU, OU=nombreorganizacion6535, CN=www.nombreorganizacion6535.org"
	right=192.168.56.101
	rightid="C=ES, ST=Murcia, O=UMU, OU=nombreorganizacion6535, CN=edu6535.org, emailAddress=edu@gmail.com"
	type=transport
	auto=start
	ah=sha1

# Sample VPN connections

#conn sample-self-signed
#      leftsubnet=10.1.0.0/16
#      leftcert=selfCert.der
#      leftsendcert=never
#      right=192.168.0.2
#      rightsubnet=10.2.0.0/16
#      rightcert=peerCert.der
#      auto=start

#conn sample-with-ca-cert
#      leftsubnet=10.1.0.0/16
#      leftcert=myCert.pem
#      right=192.168.0.2
#      rightsubnet=10.2.0.0/16
#      rightid="C=CH, O=Linux strongSwan CN=peer name"
#      auto=start
